### PR TITLE
LPS-55163

### PR DESCRIPTION
**Pull request by dustinryerson**

### CODE REVIEW

**Comment by dustinryerson** [comment]
Hey @jonathanmccann,

I should also note that a user will always have a default userCalendar, which is why I don't check to see if it's null.

In addition to [LPS-55163](https://issues.liferay.com/browse/LPS-55163), this fix also resolves [LPS-55164](https://issues.liferay.com/browse/LPS-55164) and [LPS-55165](https://issues.liferay.com/browse/LPS-55165)

Please let me know if you have any questions.

Thanks! :rocket:

**Comment by jonathanmccann** [comment]
We don't even need to check if groupCalendars is null/empty since we're just looping over it, right?

**Comment by dustinryerson** [comment]
Let me do a few more tests just to be sure and I'll get back to you on that.

**Comment by dustinryerson** [comment]
So in my testing I've seen that it's possible to have multiple userCalendars but no groupCalendars, so I think there is a case for having the null/empty check, but I'm not sure how much this affects performance.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Adam for further review: https://github.com/brandizzi/liferay-plugins/pull/82

**Pull request closed without merging**
