### PR TITLE
Lps 58384

### PR DESCRIPTION
**Pull request by arbetts**
i discovered that i missed the equals sign when doing the back port to 6.2.x

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Andrew,

**Please run ant format-source.** I already have said this on multiple pull requests and even did so on the last one for this LPS.

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/johnnyhowey/liferay-plugins/pull/726

**Comment by arbetts** [comment]
i'll add ant format-source to my git push script

**Comment by arbetts** [comment]
function added to git commit

**Pull request closed without merging**
