### PR TITLE
Lps 58384

### PR DESCRIPTION
**Pull request by arbetts**
since I was not able to test this in master (i got a compile error for the notifications portlet because of main.scss 

```
     [echo] Exception in thread "main" com.liferay.sass.compiler.jni.internal.JniSassCompilerException: com.liferay.sass.compiler.jni.internal.JniSassCompilerException: Error: file to import not found or unreadable: bourbon
     [echo]        Current dir: /private/var/folders/pf/ffbkpwcj1y3dqskb466vyg5h0000gn/T/
     [echo]         on line 1 of ../../../../../../../private/var/folders/pf/ffbkpwcj1y3dqskb466vyg5h0000gn/T/tmp2920028965688493168.scss
     [echo] >> @import "bourbon";
     [echo]    --------^
     [echo] 
     [echo] 	at com.liferay.sass.compiler.jni.internal.JniSassCompiler.compileString(JniSassCompiler.java:154)
     [echo] 	at com.liferay.css.builder.CSSBuilder._parseSass(CSSBuilder.java:327)
     [echo] 	at com.liferay.css.builder.CSSBuilder._addSassString(CSSBuilder.java:154)
     [echo] 	at com.liferay.css.builder.CSSBuilder._parseSassFile(CSSBuilder.java:427)
     [echo] 	at com.liferay.css.builder.CSSBuilder._build(CSSBuilder.java:176)
     [echo] 	at com.liferay.css.builder.CSSBuilder.execute(CSSBuilder.java:122)
     [echo] 	at com.liferay.css.builder.CSSBuilder.main(CSSBuilder.java:94)
     [echo] Caused by: com.liferay.sass.compiler.jni.internal.JniSassCompilerException: Error: file to import not found or unreadable: bourbon
     [echo]        Current dir: /private/var/folders/pf/ffbkpwcj1y3dqskb466vyg5h0000gn/T/
     [echo]         on line 1 of ../../../../../../../private/var/folders/pf/ffbkpwcj1y3dqskb466vyg5h0000gn/T/tmp2920028965688493168.scss
     [echo] >> @import "bourbon";
     [echo]    --------^
     [echo] 
     [echo] 	at com.liferay.sass.compiler.jni.internal.JniSassCompiler.compileFile(JniSassCompiler.java:113)
     [echo] 	at com.liferay.sass.compiler.jni.internal.JniSassCompiler.compileString(JniSassCompiler.java:150)
     [echo] 	... 6 more
```

I had to bring this code into 6.2.x to test. and it worked there.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
The notifications portlet is building successfully for me now. Would you mind testing this out real quick to confirm it fixes the issue on Master too? Thanks.

**Comment by arbetts** [comment]
will test this now, thanks

**Comment by arbetts** [comment]
@jonathanmccann 
i have been able to successfully deploy the notifications portlet but i have not been able to test the issue.

I have tried deploying different portlets that have notifications but I cannot get any of them to work properly in master.

Since the code is the same for ee-6.2.x and master for the notifications portlet, can we push this through and see what John Lee says?

thanks

**Comment by jonathanmccann** [comment]
Thanks for testing. Also, please be sure to run "ant format-source".

**Comment by jonathanmccann** [comment]
Reviewed and sent to Jon for further review: https://github.com/johnnyhowey/liferay-plugins/pull/725

**Pull request closed without merging**
